### ISSUE TITLE
Value Error : You are trying to merge on object and int64 columns. if you wish to proceed, you should use pd.concat

### ISSUE THREAD

**Issue by benborges** [estebanpdl/telegram-api#2]
![image](https://user-images.githubusercontent.com/10617712/169794550-6ed109d8-362b-41f7-a885-bb82f54a559e.png)

**Comment by benborges** [comment]
@estebanpdl I havent been able to reproduce the error on my side anymore, but this one has taken center stage and happens consistently with that channel..

**Comment by estebanpdl** [comment]
This one is peculiar. Not sure if you opened this file and then ran the program again? Right now, the program saves all files in the output folder. I recommend having the `output` folder clean/empty before running a new set of channels.

**Comment by benborges** [comment]
so in between each execution the output folder should be cleaned ?

I'm asking because I need to have this "incremental" but i'm afraid If I clean the output folder it will restart from the start ?

**Comment by benborges** [comment]
I haven't tried to open the file no, because I don't know which one is concerned ?

**Comment by benborges** [comment]
This is my current output/data folder : 
![image](https://user-images.githubusercontent.com/10617712/170062574-d2e9ee48-2b0b-43fd-a72e-5716b86fc705.png)

**Comment by estebanpdl** [comment]
In this error, the problem occurred with `collected_chats.csv`. If you want to update this constantly, for now, it would be better to merge those datasets separately after each execution. Right now - for better performance - it is recommended to have the output folder clean before executing a new request.

**Comment by estebanpdl** [comment]
Just as a note, in my own research, I have been dealing a bit with updating the collected_chats file. So, I am planning to update the code into something that allows updating the new request with the previous ones, in case this is necessary.

**Comment by benborges** [comment]
I have loads of questions....

Does it mean that in between each run I can erase the whole data folder ? and it will be recreated for each run? 
and then merge, does it mean merging all the CSV and the JSON of each "data" folder run to have a unified archive ?
if that's the case I don't understand where it keeps track of channel/message id already written to the JSON

I'm confused probably

Unless the only file that stays in between run is the counter.csv ?
that would make sense

**Comment by Dhadora** [comment]
![image](https://user-images.githubusercontent.com/86198770/198849721-8650b871-8954-41d4-9247-f000d24f5d7c.png)


there is a solution?

**Comment by estebanpdl** [comment]
Hi, please clone the new updated version. I was no able to replicate the same error using the updated one.

**Comment by estebanpdl** [comment]
I'll close this issue. Some of the questions here were addressed ion the updated version of this repo. If you have new flags, please open a new issue. Thank you!
