### ISSUE TITLE
Setup.py?

### ISSUE THREAD

**Issue by KevKurian** [estebanpdl/telegram-api#4]
Setup.py is  not found, keep getting error while running pip install -r requirements.txt  that says python setup.py  bdist_wheel did not run successfully. Using Windows Powershell as command line, virtual env already setup. Any input would be greatly appreciated, thanks.

**Comment by KevKurian** [comment]
<img width="700" alt="image" src="https://user-images.githubusercontent.com/91703832/201496009-6185830f-3c11-45e3-bddd-f806be6edde9.png">

**Comment by estebanpdl** [comment]
Maybe [this](https://stackoverflow.com/questions/71470989/python-setup-py-bdist-wheel-did-not-run-successfully) could work for you. This issue is not related to the repo but to your environment.
