### ISSUE TITLE
Can it search on it's own

### ISSUE THREAD

**Issue by VasilMirov** [estebanpdl/telegram-api#7]
Hello esteban, I've been looking at your tracker project and was wondering if this is able to search on it's own for telegram channel and save it's data?

**Comment by estebanpdl** [comment]
Hi. why do you mean by _searching on its own_? Like some triggers to pull data from the channel?

**Comment by VasilMirov** [comment]
i figured it out, by using the --batch-file option it uses the channels.txt file, and it searches the messages in that list to find and pull channel/group data that have usernames, from 50 channels in that list it managed to find > 1500 channels/groups. But it saves the entire data of the channels/groups into this CSV file that doesn't contain a header. It's a very interesting approach, but why not have some sort of filter options? For example search and find channels that have groups where you can send links/pictures etc, or find channels that have subscribers > input_number. I think you can do much more.

**Comment by estebanpdl** [comment]
Thank you for your feedback. Indeed. It can be improved in so many ways. If you run `python build_datasets.py`, it creates a CSV file containing headers. Did not understand that part about the headers. But again, feedback is important. Stay tuned for updates.
